name: snapbasket
description: Gestione scontrini digitale
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & stato
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1

  # ML / immagini
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.7
  image: ^4.0.17

  # Grafici / i18n
  fl_chart: ^0.70.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/graphic.jpg
    - lib/assets/logo.png
    - lib/assets/title.png
    - lib/assets/white.png
    - lib/assets/fonts/
