// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9VTwRyWayiBSJzlUck5Us7yfuqSndnW0',
    appId: '1:1097254053977:web:807f4b8584563b2ec5a948',
    messagingSenderId: '1097254053977',
    projectId: 'snapbasket-66125',
    authDomain: 'snapbasket-66125.firebaseapp.com',
    storageBucket: 'snapbasket-66125.firebasestorage.app',
    measurementId: 'G-RL83X8WG89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGuNou3OD3VsSthd4sW7fUv0yWRrq3cxs',
    appId: '1:1097254053977:android:10d4c180851129c7c5a948',
    messagingSenderId: '1097254053977',
    projectId: 'snapbasket-66125',
    storageBucket: 'snapbasket-66125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVk-G9O13u5W-leg4WficRElWjDeZNNE',
    appId: '1:1097254053977:ios:85da62dbaf7dc899c5a948',
    messagingSenderId: '1097254053977',
    projectId: 'snapbasket-66125',
    storageBucket: 'snapbasket-66125.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJVk-G9O13u5W-leg4WficRElWjDeZNNE',
    appId: '1:1097254053977:ios:85da62dbaf7dc899c5a948',
    messagingSenderId: '1097254053977',
    projectId: 'snapbasket-66125',
    storageBucket: 'snapbasket-66125.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9VTwRyWayiBSJzlUck5Us7yfuqSndnW0',
    appId: '1:1097254053977:web:efe6ee2174cc2ec1c5a948',
    messagingSenderId: '1097254053977',
    projectId: 'snapbasket-66125',
    authDomain: 'snapbasket-66125.firebaseapp.com',
    storageBucket: 'snapbasket-66125.firebasestorage.app',
    measurementId: 'G-C2CGLLP8T4',
  );
}
