name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2' # Assicurati che questa versione includa il Dart SDK richiesto

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./helloworld

    - name: Build APK
      shell: bash
      run: |
        echo "Building APK..."
        flutter build apk --release
        echo "APK build completed."
      working-directory: ./helloworld

    - name: Run unit tests
      run: |
        echo "Running unit tests..."
        flutter test
        echo "Unit tests completed."
      working-directory: ./helloworld
